### ISSUE TITLE
Php 5.6 requirement

### ISSUE THREAD

**Issue by ctrlaltca** [fruux/sabre-event#36]
Hi, this library should requite php 5.5, but In [one of the examples](https://github.com/fruux/sabre-event/blob/master/examples/promise.php#L6) a function is imported using "use function" that is only supported from php 5.6 onwards.
This is a minor problem since it only targets one of the examples scripts, and i only noticed it when running a php5.5-based ioncube version on the code.

**Comment by evert** [comment]
I'm not too concerned about this. As you implied yourself, the examples aren't really part of the API, they are just documentation. You could consider it a friendly nudge to install a later PHP version ;)
