### ISSUE TITLE
Possible issue with then() being called when triggering $promise->reject(); 

### ISSUE THREAD

**Issue by johnnymast** [fruux/sabre-event#37]
Hi there!,

I was looking trough your promise implementation and was building my own class form it. I have a call back on then() that echo's **hello world** and when i run $promise->reject(new Exception('...')); on the promise instance also then() it triggered first.

This might lead to potential bugs right? This might be the case if you change any state of your app in a then() function.

https://github.com/fruux/sabre-event/blob/master/lib/Promise.php#L263

**Comment by johnnymast** [comment]
There is a gist of my implementation https://gist.github.com/johnnymast/3a8133cee75af3db425cde69d192236e

**Comment by johnnymast** [comment]
Never mind it was a bug of my own. I am sorry to waste your time.

**Comment by evert** [comment]
No worries =)

**Comment by evert** [comment]
P.S. I would strongly suggest not extending the object, but _using_ it instead.

**Comment by johnnymast** [comment]
I am not extending it i am tying to recode it and learn the patern.

**Comment by evert** [comment]
Ah in that case.. great idea. I only really understood the Promise once I wrote it myself ;)

**Comment by johnnymast** [comment]
This is how we all learn the best. Read learn / reverse engineer to understand why things work and then write it your self. This is how i learn most difficult things. 

PS: I saw your "Promises and generators in PHP" talk. This is how i found your software.
