### ISSUE TITLE
Coroutines should resolve with the generator return value

### ISSUE THREAD

**Issue by felixfbecker** [fruux/sabre-event#42]
PHP 7 has `Generator::getReturn()` to get the return value of a generator. That means code like this is possible:
```php
coroutine(function () {
  $x = yield someAsync();
  if ($x->whatever) {
    return 'thisvalue';
  }
  $y = yield someOtherAsync();
  if ($y->whatever) {
    return 'thatvalue';
  }
  return yield $y->whatelse();
```
But currently coroutines will always use the last `yield` value, which makes control flow like above weird.

**Comment by evert** [comment]
This is a great idea, thanks!

**Comment by felixfbecker** [comment]
References that behave the same:
https://tc39.github.io/ecmascript-asyncawait/
https://www.npmjs.com/package/co
http://bluebirdjs.com/docs/api/promise.coroutine.html

**Comment by evert** [comment]
Do you think this is possible in a backwards compatible way? Or does this mean we need to do a 6.0.0 release?

**Comment by felixfbecker** [comment]
I think it's a breaking change because it changes the semantics. Any code that does
```php
if ($whatever) {
  yield whatever();
  return;
}
```
will get `null` as resolve value (and it should be that way). Previously it would be the return value of `whatever()`.

I think it's worth it though. Nobody is forced to update after all, but those who do and new projects benefit from a lot less boilerplate, cleaner semantics and shared behavior with how other implementations work. #43 is also kind of a breaking change in case you relied on the error being thrown.

**Comment by evert** [comment]
Well I fully agree that this should happen. So lets make this a priority and cut a v5.0. Sucks a bit to have a major version just after the last, but worth it!

**Comment by staabm** [comment]
agree, just do another major release. no worries.

**Comment by felixfbecker** [comment]
ETA for 5.0?

**Comment by evert** [comment]
Just released it!
